import javax.swing.*;
import java.sql.*;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
 
/**
 *
 * @author chinm
 */
public class Home extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement ps=null,ps2=null;
    ResultSet rs=null,rs2=null;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        populateTable();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 77, 0));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HOME PAGE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel2)
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(42, 42, 42))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 130));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 77, 0), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        search.setForeground(new java.awt.Color(153, 153, 153));
        search.setText("Enter title or artist to search");
        search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel4.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 270, 40));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("    SEARCH");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 4, 70, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 850, 280));

        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        jButton2.setText("EDIT DETAILS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));
        jPanel4.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 110, 20));

        jLabel3.setText("WELCOME");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 70, 20));

        jScrollPane1.setViewportView(jPanel4);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 930, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
   
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
  
        String j=search.getText();
        Query1 q=new Query1();
        ArrayList<artsdb> list=q.BindTable(j);
        String[] columnName={"ID","TYPE","TITLE","ARTIST","COST","IMAGE"};
        Object[][] rows=new Object[list.size()][6];
        for(int i=0;i<list.size();i++)
        {
            rows[i][0]=list.get(i).getId();
            rows[i][1]=list.get(i).getType();
            rows[i][2]=list.get(i).getTitle();
            rows[i][3]=list.get(i).getArtist();
            rows[i][4]=list.get(i).getCost();
            if(list.get(i).getImg()!=null)
            {
                ImageIcon image=new ImageIcon(new ImageIcon(list.get(i).getImg()).getImage().getScaledInstance(150,120,Image.SCALE_SMOOTH));
                rows[i][5]=image;
            }
            else
                rows[i][5]=null;
        }
         
        TheModel model=new TheModel(rows,columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(120);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Login l=new Login();
        l.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        
    }//GEN-LAST:event_searchActionPerformed

    ShowImages s=new ShowImages();
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
        s.username.setText(username.getText());
        int index=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        String imageName=model.getValueAt(index,0).toString();
        s.setVisible(true);
        s.pack();
        s.setLocationRelativeTo(null);
        s.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        con=MySqlConnect.ConnectDB();
        String q1="Select ARTS_IMG from arts where TITLE='"+model.getValueAt(index,2)+"'";
        ps=con.prepareStatement(q1);
        rs=ps.executeQuery();
        if(rs.next()){
        byte[] img=rs.getBytes("ARTS_IMG");
        ImageIcon image=new ImageIcon(img);
        Image im=image.getImage();
        Image image2=im.getScaledInstance(s.ShowLabel.getWidth(),s.ShowLabel.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image3=new ImageIcon(image2);
        s.ShowLabel.setIcon(image3);
        }
        
        String s1=model.getValueAt(index,1).toString();
        String s2=model.getValueAt(index,2).toString();
        String s3=model.getValueAt(index,3).toString();
        String s4=jTable1.getValueAt(index,4).toString();
        s.setVisible(true);
        s.pack();
        s.setLocationRelativeTo(null);
        s.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        if(s1.equals("1"))
            s.type.setText("Abstract");
        if(s1.equals("2"))
            s.type.setText("Portrait");
        s.title.setText(s2);
        s.artist.setText(s3);
        s.cost.setText(s4);
        this.dispose();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    Login l=new Login();
     EditCust e=new EditCust();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
       
        e.setVisible(true);
        
        con=MySqlConnect.ConnectDB();
        String q2="Select CUS_NAME,CUS_USRNAME,CUS_PHONE,CUS_PASSWORD,CUS_ADDRESS from customer where CUS_USRNAME='"+username.getText()+"'";
        try{
            ps2=con.prepareStatement(q2);
            rs=ps2.executeQuery();
            while(rs.next())
            { 
                String i=rs.getString("CUS_NAME");
                String j=rs.getString("CUS_USRNAME");
                
                String l=rs.getString("CUS_PASSWORD");
                String m=rs.getString("CUS_ADDRESS");
                e.setVisible(true);
                e.pack();
                e.setLocationRelativeTo(null);
                e.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                e.name.setText(i);
                e.username.setText(j);
                e.phone.setText(rs.getString("CUS_PHONE"));
                e.password.setText(l);
                e.address.setText(m);
                
            }
        }
        catch(Exception x)
        {
            JOptionPane.showMessageDialog(null,x);
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        if(search.getText()!=null)
        {
            search.setText("");
            repaint();
            revalidate();
        }
    }//GEN-LAST:event_searchMouseClicked
    
    
    
    public void populateTable()
    {
        Query q=new Query();
        ArrayList<artsdb> list=q.BindTable();
        String[] columnName={"ID","TYPE","TITLE","ARTIST","COST","IMAGE"};
        Object[][] rows=new Object[list.size()][6];
        for(int i=0;i<list.size();i++)
        {
            rows[i][0]=list.get(i).getId();
            rows[i][1]=list.get(i).getType();
            rows[i][2]=list.get(i).getTitle();
            rows[i][3]=list.get(i).getArtist();
            rows[i][4]=list.get(i).getCost();
            if(list.get(i).getImg()!=null)
            {
                ImageIcon image=new ImageIcon(new ImageIcon(list.get(i).getImg()).getImage().getScaledInstance(150,120,Image.SCALE_SMOOTH));
                rows[i][5]=image;
            }
            else
                rows[i][5]=null;
        } 
         
        TheModel model=new TheModel(rows,columnName);
        jTable1.setModel(model);
        jTable1.setRowHeight(120);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField search;
    public javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
