import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
 import net.proteanit.sql.DbUtils;
 

/**
 *
 * @author chinm
 */
public class ViewCust extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement ps=null,ps2=null;
    ResultSet rs=null,rs2=null;
    /**
     * Creates new form ViewCust
     */
    public ViewCust() {
        initComponents();
        this.setLocationRelativeTo(null);
        showTable();
    }
     
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        username1 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        phone1 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        address1 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jButtonAdd = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 77, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" CUSTOMER DETAILS");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 410, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cust.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 130));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 77, 0), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("FULL NAME:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, -1));

        name1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 210, 20));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 82, 220, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("USERNAME:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 70, -1));

        username1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username1ActionPerformed(evt);
            }
        });
        jPanel2.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 220, 20));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("PASSWORD:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        password1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 220, 20));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 220, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("PHONE NUMBER:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 100, -1));

        phone1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phone1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 220, -1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 220, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("ADDRESS:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 110, -1));

        address1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 220, 20));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 220, 10));

        jButtonAdd.setText("ADD");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        jButtonBack.setText("BACK");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUST_ID", "FULL NAME", "USERNAME", "PASSWORD", "PHONE NO", "ADDRESS"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(5).setMinWidth(100);
            jTable.getColumnModel().getColumn(5).setMaxWidth(1000);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 590, 430));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1010, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username1ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        con=MySqlConnect.ConnectDB();
        String q1="insert into customer(cus_name,cus_usrname,cus_phone,cus_password,cus_address) values(?,?,?,?,?)";
        String q2="insert into login(login_id,password,login_type) values(?,?,'cust')";
        try{
            ps2=con.prepareStatement(q2);
            ps2.setString(1,username1.getText());
            ps2.setString(2,password1.getText());
            ps=con.prepareStatement(q1);
            ps.setString(1,name1.getText());
            ps.setString(2,username1.getText());
            ps.setString(3,phone1.getText());
            ps.setString(4,password1.getText());
            ps.setString(5,address1.getText());

            ps2.execute();
            ps.execute();
            
            name1.setText("");
            username1.setText("");
            phone1.setText("");
            password1.setText("");
            address1.setText("");
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        showTable();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         con=MySqlConnect.ConnectDB();
        String q1="delete from customer where cus_usrname=?";
        String q2="delete from login where login_id=?";
        try{
            ps2=con.prepareStatement(q2);
            ps2.setString(1,username1.getText());
            ps=con.prepareStatement(q1);
            ps.setString(1,username1.getText());
            
            ps2.execute();
            ps.execute();
             name1.setText("");
            username1.setText("");
            phone1.setText("");
            password1.setText("");
            address1.setText("");
            
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        showTable();
    }//GEN-LAST:event_deleteActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        Admin a=new Admin();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        int index=jTable.getSelectedRow();
        TableModel model=jTable.getModel();
        String s1=model.getValueAt(index,1).toString();
        String s2=model.getValueAt(index,2).toString();
        String s3=model.getValueAt(index,3).toString();
        String s4=model.getValueAt(index,4).toString();
        String s5=model.getValueAt(index,5).toString();
            name1.setText(s1);
        username1.setText(s2);
        phone1.setText(s3);
        password1.setText(s4);
        address1.setText(s5);
    }//GEN-LAST:event_jTableMouseClicked
    public void showTable(){
        Customer q=new Customer();
        ArrayList<Customer> list=q.BindTable();
        String[] columnName={"ID","FULL NAME","USERNAME","PHONE NO","PASSWORD","ADDRESS"};
        Object[][] rows=new Object[list.size()][6];
        for(int i=0;i<list.size();i++)
        {
            rows[i][0]=list.get(i).getId();
            rows[i][1]=list.get(i).getType();
            rows[i][2]=list.get(i).getTitle();
            rows[i][3]=list.get(i).getCost();
            rows[i][4]=list.get(i).getArtist();
            rows[i][5]=list.get(i).getAdd();
        } 
         
        TheModel model=new TheModel(rows,columnName);
        jTable.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCust().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address1;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField name1;
    private javax.swing.JPasswordField password1;
    private javax.swing.JTextField phone1;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables
}
